# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "168b692e948fa94548c0aeeb3d6cadf5"
name = "EasyNode"
handle = "easynode"
application_url = "https://gold-applied-excessive-married.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "easysubscription1.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://gold-applied-excessive-married.trycloudflare.com/auth/callback",
  "https://gold-applied-excessive-married.trycloudflare.com/auth/shopify/callback",
  "https://gold-applied-excessive-married.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
